spring:
  application:
    name: api-services-data
  profiles:
    active: peer1
#  datasource:
#    password: 1qaz!QAZebpps
#    url: jdbc:sqlserver://ebpps-dev.database.windows.net:1433;databaseName=ebpps-api
#    username: wivx@ebpps-dev
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    password: tpcpassword
    url: jdbc:db2://tpmdms-dev.xuzoo.net:50001/TPCMAM:currentSchema=MAXIMO;
    username: db2inst1
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
    show-sql: true       